# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dfirdark" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "DFIRScience"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Joshua I. James"
description              : "Tutorials and research about the science and practice of digital forensics and incident response."
url                      : "https://DFIR.Science"
baseurl                  : "/"
repository               : "dfirscience/dfir.science"
teaser                   : "/assets/images/logos/dfir_squaregrid_slate.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/images/logos/dfir_logo_horz_light.png"
masthead_title           : " " # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : #"cybercrimetech"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                : "6LfE7LIUAAAAAG-5Sbj0q-HBambGResuDxJRUfoo"
  secret                 : "6LfE7LIUAAAAAHf91L4dNxnWY3wJhXZp4aK76fqN"
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true #, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : "DFIRScience"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "/assets/images/logos/dfir_card.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person
  name                   : "Joshua I. James"
  links:
      - "https://twitter.com/DFIRScience"
      - "https://youtube.com/DFIRScience"
      - "https://github.com/jijames"
      - "https://linkedin.com/company/dfirscience"
      - "https://instagram.com/dfirscience"
      - "https://reddit.com/u/dfirscience"
      - "https://infosec.exchange/@dfirscience"
      - "https://facebook.com/dfirscience"
      - "https://www.tiktok.com/@dfirscience"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : 
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Joshua I. James"
  avatar           : #"/assets/images/REAPERlogo.png"
  bio              : "Digital Forensic Scientist"
  location         :
  email            :
  links:
    - label: "Newsletter"
      icon: "fas fa-fw fa-envelope"
      url: "http://eepurl.com/hG9inj"
    - label: "Youtube"
      icon: "fab fa-yt fa-youtube"
      url: "https://www.youtube.com/DFIRScience?sub_confirmation=1"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/DFIRScience"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DFIRScience"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/company/dfirscience"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://reddit.com/u/dfirscience"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: https://us5.list-manage.com/contact-form?u=3664f5bc2c4350bc7454f233d&form_id=42749486e45c8394701634ff776be7b8
    - label: "Support"
      icon: "fab fa-patreon"
      url: https://www.patreon.com/dfirscience

# Site Footer
footer:
  links:
    - label: "Youtube"
      icon: "fab fa-yt fa-youtube"
      url: "https://www.youtube.com/DFIRScience?sub_confirmation=1"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/DFIRScience"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/company/dfirscience"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://reddit.com/u/dfirscience"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://infosec.exchange/@DFIRScience"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/DFIRScience"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/DFIRScience"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:year/:month/:title.html
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Seoul"


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
#category_archive:
#  type: liquid
#  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _python
  - scope:
      path: ""
      type: python
    values:
      layout: single
      classes: wide
      author_profile: false
      share: true
      sidebar:
        nav: "courses"
  # _golang
  - scope:
      path: ""
      type: golang
    values:
      layout: single
      classes: wide
      author_profile: false
      share: true
      sidebar:
        nav: "courses"
  # _dfs101
  - scope:
      path: ""
      type: dfs101
    values:
      layout: single
      classes: wide
      author_profile: false
      share: true
      sidebar:
        nav: "courses"

# Collections
collections:
  python:
    output: true
    permalink: /:collection/:path/
  golang:
    output: true
    permalink: /:collection/:path/
  dfs101:
    output: true
    permalink: /:collection/:path/
