blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/mmistakes/minimal-mistakes/discussions
    about: Please post your support questions in the Discussions section.