name: Cleanup bad PR

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    if: "contains(github.event.pull_request.body, 'CHECK_PR_DID_NOT_CONFIRM') || github.event.pull_request.body == ''"
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'Type: Invalid'
      - uses: superbrothers/close-pull-request@v3
        with:
          # Optional. Post an issue comment just before closing a pull request.
          comment: "This PR is not valid for inclusion. Please check again if you're submitting improvements for *the theme*."
